import type { CaseDefinition } from "../types";

export const lastCommitCase: CaseDefinition = {
  meta: {
    id: "last-commit",
    title: "The Last Commit",
    tagline: "A founder traces a stolen model to her own boardroom — and doesn't live to name who.",
    difficulty: "advanced",
    victim: {
      name: "Naomi Reyes",
      role: "Founder & CEO, Cipher Dynamics",
      age: 38,
      causeOfDeath: "Blunt force trauma during a struggle in the company server lab.",
      timeOfDeath: "Between 10:54 PM and 12:15 AM",
    },
    premise:
      "A stealth AI startup's flagship model is leaked to a rival lab three nights before its funding round closes. When the founder traces the leak to someone in her own boardroom, she turns up dead in the server lab hours later. The player must interview the CTO, the head of product, and the lead investor, uncover who actually leaked the model, and determine who killed her to keep it buried.",
    crimeSceneSummary:
      "Naomi Reyes was found dead in Cipher Dynamics' server lab just after midnight, hours after the board meeting that was supposed to finalize the company's Series B term sheet. The room showed signs of a struggle: a snapped monitor arm, scattered cable ties, and an overturned equipment cart. Her badge and laptop were still on the desk. The lab's advisor-tier access log — a credential tier she thought she'd revoked months ago — told a very different story than anyone in the room was willing to.",
    knownFacts: [
      "Three nights before the Series B term sheet was set to close, Cipher Dynamics' flagship model, Nightfall, was leaked to a rival lab.",
      "Naomi called an emergency board meeting the evening of her death, saying she'd traced the leak to 'someone in this room.'",
      "The server lab requires either an engineering badge or a legacy advisor-tier credential, both logged automatically.",
      "Naomi's calendar shows she planned to meet the full board again the next morning with 'documentation.'",
      "A Slack status she set an hour before her death read: 'Meeting D. alone tonight to confront him.'",
    ],
    initialEvidenceIds: ["building-access-log", "broken-monitor-arm"],
    orionBriefing:
      "Detective, new case. Naomi Reyes — founder and CEO of Cipher Dynamics — found dead in her own server lab hours after her flagship model leaked to a rival lab. Three people in that boardroom had a reason to want the truth buried: her CTO, her head of product, and her lead investor. One of them didn't just have a motive — they had the access. I'll flag contradictions as you catch them. The rest is on you, Detective.",
  },

  suspects: [
    {
      id: "marcus-webb",
      name: "Marcus Webb",
      role: "Chief Technology Officer",
      motive:
        "Naomi was preparing to split his sole-inventor credit on the Nightfall model with a junior engineer, jeopardizing his equity acceleration.",
      personality: "Guarded, technical, quietly resentful.",
      secret:
        "He interviewed with Cipher's rival lab weeks before the leak, and stepped out the night of the murder to meet a recruiter in person and formally turn the offer down.",
      lieStatement: "I was heads-down on a client call all evening. I never left my desk.",
      truthStatement:
        "Fine. I stepped out for forty minutes to meet a recruiter — in person, because I wanted to look her in the eye and turn the offer down. I didn't want it getting back to Naomi looking like I was still shopping myself around.",
      contradictingEvidenceId: "recruiter-calendar-invite",
      portraitInitials: "MW",
      knownTimeline: [
        "Attended the board meeting until it ended at 8:00 PM.",
        "Calendar shows a personal hold from 8:15 to 8:55 PM.",
        "Claims he never left his desk that night.",
        "Nightfall's repo history lists him as a co-author with server access to the exported files.",
      ],
      presetQuestions: [
        { id: "marcus-timeline", category: "timeline", prompt: "Walk me through your evening after the board meeting." },
        { id: "marcus-relationship", category: "relationship", prompt: "What was your working relationship with Naomi like?" },
        { id: "marcus-motive", category: "motive", prompt: "Did Naomi say anything about changing credit on the Nightfall project?" },
        { id: "marcus-alibi", category: "alibi", prompt: "Where were you between eight and eleven that night?" },
        { id: "marcus-evidence", category: "evidence", prompt: "Did you leave the building at any point that night?" },
        { id: "marcus-pressure", category: "pressure", prompt: "You interviewed at our biggest rival weeks before the leak, Marcus. Explain that." },
      ],
    },
    {
      id: "priya-anand",
      name: "Priya Anand",
      role: "Head of Product",
      motive:
        "Naomi discovered Priya quietly inflated the engagement metrics in the Series B deck and was about to correct the numbers with the full board.",
      personality: "Poised, evasive, protective of the company's narrative.",
      secret:
        "She slipped back into the office after the board meeting to try to walk back an inflated metric before anyone cross-checked it.",
      lieStatement: "I left right after the board meeting and went straight home.",
      truthStatement:
        "I went back up for ten minutes. I wanted to soften one number in the dashboard before Thursday's investor call — not erase it, just round it down to something defensible. That's all it was.",
      contradictingEvidenceId: "building-access-log",
      portraitInitials: "PA",
      knownTimeline: [
        "Presented the metrics section during the board meeting.",
        "Claims she left the building immediately after the meeting ended.",
        "Building access log shows her badge re-entering at 9:30 PM.",
        "Metrics dashboard history shows an undisclosed edit made the night before the pitch.",
      ],
      presetQuestions: [
        { id: "priya-timeline", category: "timeline", prompt: "What did you do after the board meeting ended?" },
        { id: "priya-relationship", category: "relationship", prompt: "How would you describe your relationship with Naomi?" },
        { id: "priya-motive", category: "motive", prompt: "Did Naomi raise any concerns about the investor deck?" },
        { id: "priya-alibi", category: "alibi", prompt: "Can anyone confirm you went straight home?" },
        { id: "priya-evidence", category: "evidence", prompt: "Did you make any changes to the metrics dashboard recently?" },
        { id: "priya-pressure", category: "pressure", prompt: "Your badge shows you back in this building at 9:30 PM. Why lie about that?" },
      ],
    },
    {
      id: "daniel-cho",
      name: "Daniel Cho",
      role: "Lead Investor, Board Observer Seat",
      motive:
        "Naomi had traced a short position on the rival lab's shares back to Daniel, timed almost exactly with the Nightfall leak, and was about to bring it to the rest of the board.",
      personality: "Charismatic, controlled, subtly threatening when cornered.",
      secret:
        "He used a legacy advisor-tier badge Naomi never revoked to access the server lab, export the Nightfall weights himself, and short the rival's shares before the leak became public.",
      lieStatement: "I left right after the board meeting ended and was home by nine.",
      truthStatement:
        "You already have the access log, so let's not do this. I went back in. I needed to know how much Naomi actually knew before the rest of the board heard it from her instead of me.",
      contradictingEvidenceId: "advisor-access-log",
      portraitInitials: "DC",
      knownTimeline: [
        "Sat through the full board meeting, which ended at 8:00 PM.",
        "Claims he left immediately and was home by nine.",
        "Advisor-tier badge opened the server lab door at 10:52 PM.",
        "Parking garage camera shows his car still on-site at 11:47 PM.",
      ],
      presetQuestions: [
        { id: "daniel-timeline", category: "timeline", prompt: "What did you do after the board meeting ended?" },
        { id: "daniel-relationship", category: "relationship", prompt: "How well did you know Naomi outside of board business?" },
        { id: "daniel-motive", category: "motive", prompt: "Did Naomi confront you about anything recently?" },
        { id: "daniel-alibi", category: "alibi", prompt: "Can anyone confirm you were home by nine?" },
        { id: "daniel-evidence", category: "evidence", prompt: "Why would your credentials open the server lab that night?" },
        { id: "daniel-pressure", category: "pressure", prompt: "Your car was still in the garage at quarter to midnight, Daniel. Explain that." },
      ],
    },
  ],

  evidence: [
    {
      id: "building-access-log",
      title: "Building Access Log — Board Night",
      description:
        "Badge scans for the executive floor and server lab on board-meeting night. Shows Marcus exiting at 8:15 PM, Priya's badge re-entering at 9:30 PM, and general floor traffic through midnight.",
      category: "access-record",
      discoveredAt: "12:10 AM — building security",
      relatedSuspects: ["marcus-webb", "priya-anand", "daniel-cho"],
      contradictionTags: ["priya-reentry"],
      unlocked: true,
      importanceLevel: "high",
      sourceLocation: "Building security office",
    },
    {
      id: "broken-monitor-arm",
      title: "Broken Monitor Arm, Server Lab",
      description:
        "A snapped monitor arm and scattered cable ties near the server lab workstation. Consistent with a struggle, not an accident.",
      category: "physical",
      discoveredAt: "12:05 AM — crime scene",
      relatedSuspects: [],
      contradictionTags: [],
      unlocked: true,
      importanceLevel: "medium",
      sourceLocation: "Cipher Dynamics server lab",
    },
    {
      id: "advisor-access-log",
      title: "Advisor-Tier Access Log",
      description:
        "Naomi never revoked Daniel's legacy advisor-tier badge grant after he joined the board. The log shows that credential opening the server lab door at 10:52 PM — the same window the model files were copied.",
      category: "access-record",
      discoveredAt: "1:20 AM — IT operations",
      relatedSuspects: ["daniel-cho"],
      contradictionTags: ["daniel-advisor-access"],
      unlocked: false,
      importanceLevel: "critical",
      sourceLocation: "Cipher Dynamics IT operations",
    },
    {
      id: "nightfall-repo-history",
      title: "Nightfall Repo Commit History",
      description:
        "Version-control history for the Nightfall model shows its full weights were exported to an external drive at 10:54 PM using the same advisor-tier credentials — two minutes after the server lab door opened.",
      category: "digital",
      discoveredAt: "1:35 AM — engineering audit",
      relatedSuspects: ["marcus-webb", "daniel-cho"],
      contradictionTags: [],
      unlocked: false,
      importanceLevel: "critical",
      sourceLocation: "Cipher Dynamics internal git server",
    },
    {
      id: "metrics-dashboard-history",
      title: "Metrics Dashboard Edit History",
      description:
        "Version history for the investor metrics dashboard shows an undisclosed edit inflating weekly active users, timestamped the night before the Series B pitch.",
      category: "digital",
      discoveredAt: "2:00 AM — product analytics",
      relatedSuspects: ["priya-anand"],
      contradictionTags: [],
      unlocked: false,
      importanceLevel: "medium",
      sourceLocation: "Cipher Dynamics analytics platform",
    },
    {
      id: "deleted-dm-thread",
      title: "Deleted Slack DM Thread",
      description:
        "Recovered DMs from Naomi to an unnamed board contact: 'The short positions match the leak timing exactly. We need to talk before the board does.' Sent at 9:52 PM, the night of her death.",
      category: "digital",
      discoveredAt: "2:20 AM — Slack export recovery",
      relatedSuspects: ["daniel-cho"],
      contradictionTags: [],
      unlocked: false,
      importanceLevel: "critical",
      sourceLocation: "Cipher Dynamics workspace backup",
    },
    {
      id: "recruiter-calendar-invite",
      title: "Recruiter Calendar Invite",
      description:
        "A calendar hold titled 'Coffee — personal' for 8:15–8:55 PM the night of the murder. The recruiter listed confirms Marcus met her in person to formally turn down an offer from Cipher's rival lab.",
      category: "document",
      discoveredAt: "2:40 AM — calendar export",
      relatedSuspects: ["marcus-webb"],
      contradictionTags: ["marcus-left-building"],
      unlocked: false,
      importanceLevel: "low",
      sourceLocation: "Marcus Webb's work calendar",
    },
    {
      id: "brokerage-confirmation",
      title: "Brokerage Confirmation Printout",
      description:
        "A trade confirmation showing Daniel opened a short position on the rival lab's secondary shares two days before the Nightfall leak went public — a bet that only pays off if the rival's valuation drops.",
      category: "document",
      discoveredAt: "2:55 AM — subpoenaed brokerage records",
      relatedSuspects: ["daniel-cho"],
      contradictionTags: [],
      unlocked: false,
      importanceLevel: "high",
      sourceLocation: "Daniel Cho's brokerage account",
    },
    {
      id: "naomi-final-message",
      title: "Naomi's Final Status Update",
      description:
        "Naomi's last Slack status, set at 10:40 PM: 'Meeting D. alone tonight to confront him. If I'm wrong about this I'll delete it tomorrow.'",
      category: "digital",
      discoveredAt: "1:50 AM — Slack export recovery",
      relatedSuspects: ["daniel-cho"],
      contradictionTags: [],
      unlocked: false,
      importanceLevel: "critical",
      sourceLocation: "Cipher Dynamics workspace backup",
    },
    {
      id: "parking-garage-still-2",
      title: "Parking Garage Camera Still",
      description:
        "A parking garage camera still timestamped 11:47 PM shows Daniel Cho's car still parked in the visitor garage — nearly three hours after he claims he left.",
      category: "physical",
      discoveredAt: "1:05 AM — garage security footage",
      relatedSuspects: ["daniel-cho"],
      contradictionTags: ["daniel-parking-garage"],
      unlocked: false,
      importanceLevel: "high",
      sourceLocation: "Visitor parking garage, level 1",
    },
  ],

  timeline: [
    {
      id: "board-meeting-ends",
      time: "8:00 PM",
      sortKey: 2000,
      title: "Board Meeting Ends",
      description:
        "Naomi closes the emergency meeting by telling the board she's traced 'irregularities' to someone in the room, without naming names yet.",
      relatedSuspects: ["marcus-webb", "priya-anand", "daniel-cho"],
      relatedEvidence: ["building-access-log"],
      confirmed: true,
      contested: false,
    },
    {
      id: "marcus-steps-out",
      time: "8:15 PM",
      sortKey: 2015,
      title: "Marcus Steps Out",
      description: "Marcus Webb leaves the building for just under an hour, claiming afterward he never left his desk.",
      relatedSuspects: ["marcus-webb"],
      relatedEvidence: ["recruiter-calendar-invite"],
      confirmed: false,
      contested: true,
      resolvesWithTag: "marcus-left-building",
    },
    {
      id: "priya-badge-reentry",
      time: "9:30 PM",
      sortKey: 2130,
      title: "Priya's Badge Re-Enters the Building",
      description: "Priya Anand's badge scans back into the office, despite her claim that she went straight home.",
      relatedSuspects: ["priya-anand"],
      relatedEvidence: ["building-access-log"],
      confirmed: false,
      contested: true,
      resolvesWithTag: "priya-reentry",
    },
    {
      id: "naomi-dm-sent",
      time: "9:52 PM",
      sortKey: 2152,
      title: "Naomi Sends a Warning DM",
      description: "Naomi messages a board contact that the short-sale timing lines up exactly with the leak.",
      relatedSuspects: ["daniel-cho"],
      relatedEvidence: ["deleted-dm-thread"],
      confirmed: false,
      contested: false,
    },
    {
      id: "daniel-lab-access",
      time: "10:52 PM",
      sortKey: 2252,
      title: "Daniel's Credentials Open the Server Lab",
      description: "A legacy advisor-tier badge — issued to Daniel Cho and never revoked — unlocks the server lab door.",
      relatedSuspects: ["daniel-cho"],
      relatedEvidence: ["advisor-access-log"],
      confirmed: false,
      contested: true,
      resolvesWithTag: "daniel-advisor-access",
    },
    {
      id: "model-exported",
      time: "10:54 PM",
      sortKey: 2254,
      title: "Nightfall Model Weights Exported",
      description: "The Nightfall repository logs a full export of the model weights to an external drive.",
      relatedSuspects: ["daniel-cho"],
      relatedEvidence: ["nightfall-repo-history"],
      confirmed: false,
      contested: false,
    },
    {
      id: "daniel-car-still-parked",
      time: "11:47 PM",
      sortKey: 2347,
      title: "Daniel's Car Still in the Garage",
      description: "A camera still places Daniel Cho's car in the visitor garage, nearly three hours after he claims he left.",
      relatedSuspects: ["daniel-cho"],
      relatedEvidence: ["parking-garage-still-2"],
      confirmed: false,
      contested: true,
      resolvesWithTag: "daniel-parking-garage",
    },
    {
      id: "body-discovered",
      time: "12:15 AM",
      sortKey: 2415,
      title: "Body Discovered",
      description: "An overnight security sweep finds Naomi Reyes's body in the server lab.",
      relatedSuspects: [],
      relatedEvidence: ["broken-monitor-arm"],
      confirmed: true,
      contested: false,
    },
  ],

  contradictions: [
    {
      id: "marcus-left-building",
      suspectId: "marcus-webb",
      triggerEvidenceId: "recruiter-calendar-invite",
      claimText: "I was heads-down on a client call all evening. I never left my desk.",
      proofText:
        "A recruiter's calendar invite confirms Marcus stepped out from 8:15 to 8:55 PM for an in-person meeting, squarely inside the leak window.",
      contradictionTag: "marcus-left-building",
      pressureDelta: 20,
      truthDelta: -25,
      trustDelta: -8,
      unlocksDialogueId: "marcus-calendar-response",
    },
    {
      id: "priya-reentry",
      suspectId: "priya-anand",
      triggerEvidenceId: "building-access-log",
      claimText: "I left right after the board meeting and went straight home.",
      proofText:
        "The building access log shows Priya's badge re-entering the office at 9:30 PM, over an hour after she says she left.",
      contradictionTag: "priya-reentry",
      pressureDelta: 22,
      truthDelta: -28,
      trustDelta: -10,
      unlocksDialogueId: "priya-badge-response",
    },
    {
      id: "daniel-advisor-access",
      suspectId: "daniel-cho",
      triggerEvidenceId: "advisor-access-log",
      claimText: "I left right after the board meeting ended and was home by nine.",
      proofText:
        "The server lab's advisor-tier access log shows Daniel's credentials opening the door at 10:52 PM — the exact window the Nightfall model was copied.",
      contradictionTag: "daniel-advisor-access",
      pressureDelta: 30,
      truthDelta: -35,
      trustDelta: -15,
      unlocksDialogueId: "daniel-access-response",
    },
    {
      id: "daniel-parking-garage",
      suspectId: "daniel-cho",
      triggerEvidenceId: "parking-garage-still-2",
      claimText: "I left right after the board meeting ended and was home by nine.",
      proofText: "A parking garage camera still shows Daniel Cho's car still on-site at 11:47 PM.",
      contradictionTag: "daniel-parking-garage",
      pressureDelta: 25,
      truthDelta: -30,
      trustDelta: -12,
      unlocksDialogueId: "daniel-garage-response",
    },
  ],

  motiveOptions: [
    { id: "credit-and-equity-dispute", label: "Silencing exposure over stolen model credit", suspectId: "marcus-webb" },
    { id: "metrics-fraud-coverup", label: "Covering up inflated investor metrics", suspectId: "priya-anand" },
    { id: "insider-trading-coverup", label: "Covering up insider trading on the model leak", suspectId: "daniel-cho" },
  ],

  requiredEvidenceIds: [
    "advisor-access-log",
    "nightfall-repo-history",
    "deleted-dm-thread",
    "naomi-final-message",
  ],

  supportingEvidenceIds: ["brokerage-confirmation", "parking-garage-still-2"],

  timelineExplanationOptions: [
    {
      id: "daniel-returned",
      label:
        "Daniel never left — he used his old advisor badge to get back into the server lab and confronted Naomi about what she'd found.",
      correct: true,
    },
    {
      id: "marcus-confronted",
      label: "Marcus confronted Naomi over losing sole credit on the Nightfall model.",
      correct: false,
    },
    {
      id: "priya-confronted",
      label: "Priya confronted Naomi over the inflated metrics dashboard.",
      correct: false,
    },
    {
      id: "unrelated-intruder",
      label: "An outside contractor with server lab access was responsible.",
      correct: false,
    },
  ],

  correctSuspectId: "daniel-cho",
  correctMotiveId: "insider-trading-coverup",
};
