import type { CaseDefinition } from "../types";

export const midnightLedgerCase: CaseDefinition = {
  meta: {
    id: "midnight-ledger",
    title: "The Midnight Ledger",
    tagline: "A CFO uncovers fraud hours before someone silences him for good.",
    difficulty: "standard",
    victim: {
      name: "Marcus Vale",
      role: "Chief Financial Officer, Northstar Systems",
      age: 47,
      causeOfDeath: "Blunt force trauma, struck by a heavy desk award during a struggle in his office.",
      timeOfDeath: "Between 12:03 AM and 12:45 AM",
    },
    premise:
      "A tech company CFO is found dead after discovering missing funds tied to a secret internal project. Three suspects had motive, access, and conflicting timelines. The player must interview suspects, inspect evidence, identify contradictions, reconstruct the timeline, and make the correct accusation.",
    crimeSceneSummary:
      "Marcus Vale was found dead in his 40th-floor corner office at Northstar Systems shortly before 1:00 AM. The room showed signs of a struggle: broken glass near the window, an overturned desk lamp, and a shattered service award used as the weapon. His terminal was left logged in to the finance ledger. Security found his office door unlocked and his badge still in his jacket pocket.",
    knownFacts: [
      "Marcus Vale discovered a discrepancy in Northstar's quarterly ledger three days before his death.",
      "He had scheduled private meetings with each of his three direct reports that week.",
      "The building's server room and executive floor both require badge access, logged automatically.",
      "Marcus sent an internal email an hour before his death referencing 'the shell account.'",
      "A handwritten note was found crumpled near his desk.",
    ],
    initialEvidenceIds: ["security-badge-log", "broken-glass"],
    orionBriefing:
      "Detective, I've pulled the preliminary incident report. Marcus Vale, CFO, found dead in his office just before 1 AM. Cause of death points to a struggle, not an accident. Three people had reason to want him silenced: his lead engineer, his COO, and his executive assistant. Each has a motive. Each has a gap in their story. I'll track contradictions as you find them — but the conclusion has to be yours. Let's get to work.",
  },

  suspects: [
    {
      id: "lena-cross",
      name: "Lena Cross",
      role: "Lead Engineer",
      motive: "Marcus planned to expose her unauthorized AI experiment.",
      personality: "Calm, analytical, guarded.",
      secret:
        "She accessed the server room after midnight but claims it was for a failed deployment.",
      lieStatement: "I never went into the server room that night.",
      truthStatement:
        "Fine — I was in the server room. Twice. I was trying to roll back a deployment before anyone noticed it existed.",
      contradictingEvidenceId: "security-badge-log",
      portraitInitials: "LC",
      knownTimeline: [
        "Left her desk around 10:30 PM after most of the floor had cleared.",
        "Badge shows server room access at 10:44 PM.",
        "Badge shows a second server room access at 11:52 PM.",
        "Claims she was home by 1:00 AM.",
      ],
      presetQuestions: [
        { id: "lena-timeline", category: "timeline", prompt: "Walk me through your night, minute by minute." },
        { id: "lena-relationship", category: "relationship", prompt: "What was your relationship with Marcus like?" },
        { id: "lena-motive", category: "motive", prompt: "Did Marcus have a problem with your work?" },
        { id: "lena-alibi", category: "alibi", prompt: "Where were you when Marcus was killed?" },
        { id: "lena-evidence", category: "evidence", prompt: "Did you enter the server room that night?" },
        { id: "lena-pressure", category: "pressure", prompt: "You're lying to me, Lena. I can see it." },
      ],
    },
    {
      id: "adrian-shaw",
      name: "Adrian Shaw",
      role: "Chief Operating Officer",
      motive: "Marcus found financial irregularities tied to Adrian's expansion deal.",
      personality: "Charming, defensive, polished.",
      secret: "He moved money into a shell vendor account.",
      lieStatement: "I left the dinner and went straight home. I was asleep by eleven.",
      truthStatement:
        "Okay. I went back to the office. Marcus called me, furious about Ridgeline. I went to explain it — that's all it was supposed to be.",
      contradictingEvidenceId: "parking-garage-still",
      portraitInitials: "AS",
      knownTimeline: [
        "Attended a board dinner downtown, left around 10:05 PM.",
        "Claims he drove straight home and was asleep by 11:00 PM.",
        "Parking garage camera shows his car leaving the executive garage at 12:41 AM.",
        "Deleted email thread shows Marcus demanded to speak with him at 9:15 PM about Ridgeline Consulting.",
      ],
      presetQuestions: [
        { id: "adrian-timeline", category: "timeline", prompt: "What did you do after the board dinner?" },
        { id: "adrian-relationship", category: "relationship", prompt: "How would you describe your working relationship with Marcus?" },
        { id: "adrian-motive", category: "motive", prompt: "Did Marcus raise any concerns about the expansion deal?" },
        { id: "adrian-alibi", category: "alibi", prompt: "Can anyone confirm you went straight home?" },
        { id: "adrian-evidence", category: "evidence", prompt: "What is Ridgeline Consulting?" },
        { id: "adrian-pressure", category: "pressure", prompt: "Your car left the garage after midnight, Adrian. Explain that." },
      ],
    },
    {
      id: "maya-reed",
      name: "Maya Reed",
      role: "Executive Assistant",
      motive: "Marcus threatened to fire her after finding leaked documents.",
      personality: "Nervous, observant, emotional.",
      secret:
        "She saw someone leaving Marcus's office but hid it because she feared retaliation.",
      lieStatement: "I didn't hear anything unusual. It was a quiet night.",
      truthStatement:
        "I heard shouting near the stairwell around midnight. I didn't say anything because I was scared — I thought I'd be blamed, or worse, targeted next.",
      contradictingEvidenceId: "stairwell-audio-transcript",
      portraitInitials: "MR",
      knownTimeline: [
        "Brought Marcus coffee around 9:30 PM while working late on quarterly documents.",
        "Claims she left the office by 11:30 PM and heard nothing unusual.",
        "Stairwell intercom captured raised voices at 12:03 AM near her known route home.",
        "Was seen near the executive floor as late as 11:20 PM by a night-shift janitor.",
      ],
      presetQuestions: [
        { id: "maya-timeline", category: "timeline", prompt: "What time did you leave the office?" },
        { id: "maya-relationship", category: "relationship", prompt: "How did Marcus treat you as his assistant?" },
        { id: "maya-motive", category: "motive", prompt: "Was there any tension between you and Marcus recently?" },
        { id: "maya-alibi", category: "alibi", prompt: "Did you see or hear anything unusual before you left?" },
        { id: "maya-evidence", category: "evidence", prompt: "Do you recognize this stairwell audio transcript?" },
        { id: "maya-pressure", category: "pressure", prompt: "You were seen on the executive floor at 11:20 PM. Why lie about it?" },
      ],
    },
  ],

  evidence: [
    {
      id: "security-badge-log",
      title: "Security Badge Log",
      description:
        "Executive floor badge scans for the night of the murder. Shows entry and exit timestamps for all three suspects, including a server room scan attributed to Lena Cross at 10:44 PM.",
      category: "access-record",
      discoveredAt: "12:52 AM — pulled by building security",
      relatedSuspects: ["lena-cross", "adrian-shaw", "maya-reed"],
      contradictionTags: ["lena-server-room-denial"],
      unlocked: true,
      importanceLevel: "high",
      sourceLocation: "Building security office",
    },
    {
      id: "broken-glass",
      title: "Broken Glass, CFO Office",
      description:
        "Shards from a shattered display case near the window. Consistent with a struggle. No usable fingerprints, but the spread pattern suggests the victim was pushed backward.",
      category: "physical",
      discoveredAt: "12:50 AM — crime scene",
      relatedSuspects: [],
      contradictionTags: [],
      unlocked: true,
      importanceLevel: "medium",
      sourceLocation: "Marcus Vale's office",
    },
    {
      id: "server-room-access-record",
      title: "Server Room Access Record",
      description:
        "Automated access log for the 41st-floor server room. Confirms Lena Cross's badge unlocked the door at 10:44 PM and again at 11:52 PM, both after standard hours.",
      category: "access-record",
      discoveredAt: "1:10 AM — IT operations",
      relatedSuspects: ["lena-cross"],
      contradictionTags: ["lena-server-room-denial"],
      unlocked: false,
      importanceLevel: "medium",
      sourceLocation: "IT operations center",
    },
    {
      id: "ai-project-access-logs",
      title: "AI Project Access Logs",
      description:
        "Internal logs showing Lena Cross created an unauthorized project workspace named 'Continuum' three weeks before the murder, hidden from the standard engineering audit trail.",
      category: "digital",
      discoveredAt: "1:15 AM — IT operations",
      relatedSuspects: ["lena-cross"],
      contradictionTags: [],
      unlocked: false,
      importanceLevel: "medium",
      sourceLocation: "Northstar internal servers",
    },
    {
      id: "encrypted-finance-ledger",
      title: "Encrypted Finance Ledger",
      description:
        "Marcus Vale's private ledger file, decrypted by forensic accounting. Shows a series of transfers routed through a shell vendor, 'Ridgeline Consulting,' approved under Adrian Shaw's signing authority.",
      category: "document",
      discoveredAt: "2:30 AM — forensic accounting",
      relatedSuspects: ["adrian-shaw"],
      contradictionTags: ["adrian-shell-vendor"],
      unlocked: false,
      importanceLevel: "critical",
      sourceLocation: "Marcus Vale's encrypted workstation",
    },
    {
      id: "deleted-email-thread",
      title: "Deleted Email Thread",
      description:
        "Recovered emails between Marcus Vale and Adrian Shaw. Marcus writes: 'The Ridgeline numbers don't reconcile. We need to talk tonight, before the board sees this.' Sent at 9:15 PM.",
      category: "digital",
      discoveredAt: "2:45 AM — email recovery",
      relatedSuspects: ["adrian-shaw"],
      contradictionTags: ["adrian-shell-vendor", "adrian-straight-home"],
      unlocked: false,
      importanceLevel: "critical",
      sourceLocation: "Northstar mail server backup",
    },
    {
      id: "parking-garage-still",
      title: "Parking Garage Camera Still",
      description:
        "A grainy still from the executive parking garage camera. Adrian Shaw's car is shown leaving the garage at 12:41 AM — not at 10:30 PM as he claims.",
      category: "physical",
      discoveredAt: "1:40 AM — garage security footage",
      relatedSuspects: ["adrian-shaw"],
      contradictionTags: ["adrian-straight-home"],
      unlocked: false,
      importanceLevel: "high",
      sourceLocation: "Parking garage, level B2",
    },
    {
      id: "coffee-cup-lipstick",
      title: "Coffee Cup with Lipstick",
      description:
        "A cup found on the credenza in Marcus's office, bearing a lipstick mark matching a shade worn by Maya Reed. Suggests she was in the office earlier that evening for a legitimate reason.",
      category: "physical",
      discoveredAt: "12:55 AM — crime scene",
      relatedSuspects: ["maya-reed"],
      contradictionTags: [],
      unlocked: false,
      importanceLevel: "low",
      sourceLocation: "Marcus Vale's office",
    },
    {
      id: "stairwell-audio-transcript",
      title: "Emergency Stairwell Audio Clip Transcript",
      description:
        "Emergency stairwell intercoms record ambient audio on trigger. Transcript captures raised voices at 12:03 AM: a man's voice saying 'You don't understand what's at stake,' and a second voice, muffled, replying 'Then explain it to the board.'",
      category: "audio",
      discoveredAt: "1:55 AM — building security",
      relatedSuspects: ["maya-reed", "adrian-shaw"],
      contradictionTags: ["maya-heard-nothing"],
      unlocked: false,
      importanceLevel: "critical",
      sourceLocation: "Stairwell B emergency intercom",
    },
    {
      id: "final-note",
      title: "Marcus Vale's Final Note",
      description:
        "A handwritten note found crumpled near the desk, timestamped by the moment it was reportedly written. Reads: 'Ridgeline is Adrian's. Confronting him tonight. If something happens, look at the vendor file.'",
      category: "document",
      discoveredAt: "12:58 AM — crime scene",
      relatedSuspects: ["adrian-shaw"],
      contradictionTags: ["adrian-shell-vendor"],
      unlocked: false,
      importanceLevel: "critical",
      sourceLocation: "Marcus Vale's office floor",
    },
  ],

  timeline: [
    {
      id: "email-sent",
      time: "9:15 PM",
      sortKey: 2115,
      title: "Marcus Receives / Sends Ledger Email",
      description:
        "Marcus emails Adrian Shaw demanding an explanation for the Ridgeline Consulting discrepancy, insisting they talk before the board meeting.",
      relatedSuspects: ["adrian-shaw"],
      relatedEvidence: ["deleted-email-thread"],
      confirmed: false,
      contested: false,
    },
    {
      id: "adrian-leaves-dinner",
      time: "10:05 PM",
      sortKey: 2205,
      title: "Adrian Leaves Board Dinner",
      description: "Adrian Shaw departs the downtown board dinner, claiming he drove straight home afterward.",
      relatedSuspects: ["adrian-shaw"],
      relatedEvidence: ["parking-garage-still"],
      confirmed: false,
      contested: true,
      resolvesWithTag: "adrian-straight-home",
    },
    {
      id: "lena-badge-server-room",
      time: "10:44 PM",
      sortKey: 2244,
      title: "Lena's Badge Used Near Server Room",
      description: "Security badge logs show Lena Cross entering the 41st-floor server room after hours.",
      relatedSuspects: ["lena-cross"],
      relatedEvidence: ["security-badge-log", "server-room-access-record"],
      confirmed: false,
      contested: true,
      resolvesWithTag: "lena-server-room-denial",
    },
    {
      id: "maya-hears-argument",
      time: "11:20 PM",
      sortKey: 2320,
      title: "Maya Seen on Executive Floor",
      description: "A night-shift janitor places Maya Reed on the executive floor, despite her claim of leaving earlier.",
      relatedSuspects: ["maya-reed"],
      relatedEvidence: ["coffee-cup-lipstick"],
      confirmed: false,
      contested: true,
      resolvesWithTag: "maya-heard-nothing",
    },
    {
      id: "stairwell-audio",
      time: "12:03 AM",
      sortKey: 2403,
      title: "Emergency Stairwell Audio Captured",
      description: "Raised voices recorded near the stairwell — a confrontation about accountability to the board.",
      relatedSuspects: ["adrian-shaw", "maya-reed"],
      relatedEvidence: ["stairwell-audio-transcript"],
      confirmed: false,
      contested: false,
    },
    {
      id: "final-note-written",
      time: "12:18 AM",
      sortKey: 2418,
      title: "Marcus Sends Final Note",
      description: "Marcus writes a note naming Adrian and the Ridgeline vendor file, anticipating danger.",
      relatedSuspects: ["adrian-shaw"],
      relatedEvidence: ["final-note"],
      confirmed: false,
      contested: false,
    },
    {
      id: "server-access-changed",
      time: "12:31 AM",
      sortKey: 2431,
      title: "Server Access Logs Changed",
      description: "A second server room access event is logged, overlapping with the window of the murder.",
      relatedSuspects: ["lena-cross"],
      relatedEvidence: ["server-room-access-record"],
      confirmed: false,
      contested: false,
    },
    {
      id: "body-discovered",
      time: "12:45 AM",
      sortKey: 2445,
      title: "Body Discovered",
      description: "Security staff conducting a floor sweep discover Marcus Vale's body in his office.",
      relatedSuspects: [],
      relatedEvidence: ["broken-glass"],
      confirmed: true,
      contested: false,
    },
  ],

  contradictions: [
    {
      id: "lena-server-room-denial",
      suspectId: "lena-cross",
      triggerEvidenceId: "security-badge-log",
      claimText: "I never went into the server room that night.",
      proofText:
        "Badge logs place Lena Cross's credentials at the server room door at 10:44 PM and 11:52 PM.",
      contradictionTag: "lena-server-room-denial",
      pressureDelta: 25,
      truthDelta: -30,
      trustDelta: -10,
      unlocksDialogueId: "lena-contradiction-response",
    },
    {
      id: "adrian-shell-vendor",
      suspectId: "adrian-shaw",
      triggerEvidenceId: "encrypted-finance-ledger",
      claimText: "There's nothing unusual about Ridgeline. It's a standard vendor.",
      proofText:
        "The decrypted finance ledger shows transfers to Ridgeline Consulting approved under Adrian Shaw's signing authority, with no matching deliverables.",
      contradictionTag: "adrian-shell-vendor",
      pressureDelta: 20,
      truthDelta: -25,
      trustDelta: -10,
      unlocksDialogueId: "adrian-ledger-response",
    },
    {
      id: "adrian-straight-home",
      suspectId: "adrian-shaw",
      triggerEvidenceId: "parking-garage-still",
      claimText: "I left the dinner and went straight home. I was asleep by eleven.",
      proofText:
        "Parking garage camera footage shows Adrian Shaw's vehicle leaving the executive garage at 12:41 AM.",
      contradictionTag: "adrian-straight-home",
      pressureDelta: 30,
      truthDelta: -35,
      trustDelta: -15,
      unlocksDialogueId: "adrian-garage-response",
    },
    {
      id: "maya-heard-nothing",
      suspectId: "maya-reed",
      triggerEvidenceId: "stairwell-audio-transcript",
      claimText: "I didn't hear anything unusual. It was a quiet night.",
      proofText:
        "Emergency stairwell audio captured raised voices at 12:03 AM, directly contradicting Maya Reed's account of a quiet night.",
      contradictionTag: "maya-heard-nothing",
      pressureDelta: 25,
      truthDelta: -30,
      trustDelta: -10,
      unlocksDialogueId: "maya-audio-response",
    },
  ],

  motiveOptions: [
    { id: "financial-fraud-coverup", label: "Financial fraud cover-up", suspectId: "adrian-shaw" },
    { id: "expose-ai-experiment", label: "Silencing an unauthorized AI experiment", suspectId: "lena-cross" },
    { id: "retaliation-termination", label: "Retaliation for a threatened firing", suspectId: "maya-reed" },
  ],

  requiredEvidenceIds: [
    "encrypted-finance-ledger",
    "deleted-email-thread",
    "stairwell-audio-transcript",
    "final-note",
  ],

  supportingEvidenceIds: ["parking-garage-still", "security-badge-log"],

  timelineExplanationOptions: [
    {
      id: "adrian-returned",
      label:
        "Adrian never left — he returned to the building after the dinner and confronted Marcus about the ledger.",
      correct: true,
    },
    {
      id: "lena-confronted",
      label: "Lena confronted Marcus in the server room over her AI project.",
      correct: false,
    },
    {
      id: "maya-argument",
      label: "Maya argued with Marcus in the stairwell over her termination.",
      correct: false,
    },
    {
      id: "unrelated-intruder",
      label: "An unrelated intruder entered through the parking garage.",
      correct: false,
    },
  ],

  correctSuspectId: "adrian-shaw",
  correctMotiveId: "financial-fraud-coverup",
};
