import type { TimelineEvent } from "./types";

export const TIMELINE_EVENTS: TimelineEvent[] = [
  {
    id: "email-sent",
    time: "9:15 PM",
    sortKey: 2115,
    title: "Marcus Receives / Sends Ledger Email",
    description:
      "Marcus emails Adrian Shaw demanding an explanation for the Ridgeline Consulting discrepancy, insisting they talk before the board meeting.",
    relatedSuspects: ["adrian-shaw"],
    relatedEvidence: ["deleted-email-thread"],
    confirmed: false,
    contested: false,
  },
  {
    id: "adrian-leaves-dinner",
    time: "10:05 PM",
    sortKey: 2205,
    title: "Adrian Leaves Board Dinner",
    description: "Adrian Shaw departs the downtown board dinner, claiming he drove straight home afterward.",
    relatedSuspects: ["adrian-shaw"],
    relatedEvidence: ["parking-garage-still"],
    confirmed: false,
    contested: true,
    resolvesWithTag: "adrian-straight-home",
  },
  {
    id: "lena-badge-server-room",
    time: "10:44 PM",
    sortKey: 2244,
    title: "Lena's Badge Used Near Server Room",
    description: "Security badge logs show Lena Cross entering the 41st-floor server room after hours.",
    relatedSuspects: ["lena-cross"],
    relatedEvidence: ["security-badge-log", "server-room-access-record"],
    confirmed: false,
    contested: true,
    resolvesWithTag: "lena-server-room-denial",
  },
  {
    id: "maya-hears-argument",
    time: "11:20 PM",
    sortKey: 2320,
    title: "Maya Seen on Executive Floor",
    description: "A night-shift janitor places Maya Reed on the executive floor, despite her claim of leaving earlier.",
    relatedSuspects: ["maya-reed"],
    relatedEvidence: ["coffee-cup-lipstick"],
    confirmed: false,
    contested: true,
    resolvesWithTag: "maya-heard-nothing",
  },
  {
    id: "stairwell-audio",
    time: "12:03 AM",
    sortKey: 2403,
    title: "Emergency Stairwell Audio Captured",
    description: "Raised voices recorded near the stairwell — a confrontation about accountability to the board.",
    relatedSuspects: ["adrian-shaw", "maya-reed"],
    relatedEvidence: ["stairwell-audio-transcript"],
    confirmed: false,
    contested: false,
  },
  {
    id: "final-note-written",
    time: "12:18 AM",
    sortKey: 2418,
    title: "Marcus Sends Final Note",
    description: "Marcus writes a note naming Adrian and the Ridgeline vendor file, anticipating danger.",
    relatedSuspects: ["adrian-shaw"],
    relatedEvidence: ["final-note"],
    confirmed: false,
    contested: false,
  },
  {
    id: "server-access-changed",
    time: "12:31 AM",
    sortKey: 2431,
    title: "Server Access Logs Changed",
    description: "A second server room access event is logged, overlapping with the window of the murder.",
    relatedSuspects: ["lena-cross"],
    relatedEvidence: ["server-room-access-record"],
    confirmed: false,
    contested: false,
  },
  {
    id: "body-discovered",
    time: "12:45 AM",
    sortKey: 2445,
    title: "Body Discovered",
    description: "Security staff conducting a floor sweep discover Marcus Vale's body in his office.",
    relatedSuspects: [],
    relatedEvidence: ["broken-glass"],
    confirmed: true,
    contested: false,
  },
];

export function getTimelineEventById(id: string): TimelineEvent | undefined {
  return TIMELINE_EVENTS.find((e) => e.id === id);
}
